language: cpp

sudo: false

matrix:
  include:
    - os: linux
      env:
       -
    - os: linux
      env:
      compiler: clang
    ## Test on Mac OS X 10.14
    - os: osx
      osx_image: xcode10.2
      before_script:
       - brew update
       - brew cask install mactex-no-gui
       - brew install texinfo
       - export PATH="/Library/TeX/texbin:$PATH"
    ## With homebrew gcc
    - os: osx
      compiler: clang
      before_install:
       - brew update
       - brew cask install mactex-no-gui
       - brew install texinfo
       - export PATH="/Library/TeX/texbin:$PATH"
       - brew install llvm || brew outdated llvm || brew upgrade llvm
       - export PATH="`brew --prefix`/opt/llvm/bin/:$PATH"
       - export LDFLAGS="-L`brew --prefix`/opt/llvm/lib -Wl,-rpath,`brew --prefix`/opt/llvm/lib"
      env: COMPILER_OVERRIDE=homebrew-llvm
    ## Test on Mac OS X 10.13
    - os: osx
      osx_image: xcode9.4
      before_script:
       - brew update
       - brew cask install mactex-no-gui
       - brew install texinfo
       - export PATH="/Library/TeX/texbin:$PATH"
    ## Test on Mac OS X 10.12
    - os: osx
      osx_image: xcode9.2
      before_script:
       - brew update
       - brew cask install mactex-no-gui
       - brew install texinfo
       - export PATH="/Library/TeX/texbin:$PATH"
    ## Test on Mac OS X 10.11
    - os: osx
      osx_image: xcode8
      before_script:
       - brew update
       - brew cask install mactex-no-gui
       - brew install texinfo
       - export PATH="/Library/TeX/texbin:$PATH"
    ## Test on Mac OS X 10.10
    - os: osx
      osx_image: xcode6.4
      before_script:
       - brew update
       - brew cask install mactex-no-gui
       - brew install texinfo
       - export PATH="/Library/TeX/texbin:$PATH"
    ## Test on 32 bit
    - services:
      - docker
      env:
       - DOCKER=i386/ubuntu

addons:
  apt_packages:
      - libgmp-dev
      - autoconf
      - automake
      - libtool
      - texlive
      - texinfo

script: ./.travis-build.sh
